README.mkd
* Update plugin location
* Root directory is now the plugin directory, so remove `rtp` settings and
`make`'s `-C` option
* Update list of build commands for NeoBundle
* `unix` entry in NeoBundle `build` setting is a synonym for `!windows` and as
building isn't different between OSX and Linux, `mac` and `linux` entries
are superfluous
=> Update vim-plug/NeoBundle usage instructions

syntax/fsharp.vim
I'm a bit new to vim but these changes seem to handle #5.
Also handles when you do (*) (i.e. try to use the multiplication operator as a function) and you get a similiar issue where the rest of the code is commented out.
=> Handle quotes within triple quotes and (*)

syntax/fsharp.vim
Verbatim strings (`@"C:\File\Path\Here\"`) aren't being syntax highlighted correctly; this isn't really noticeable until a verbatim string ends with an escaped quote. Used #14 as a reference, as I'm not super familiar with vimscript or syntax files either. :grin: 
Before:
After:
=> Handle verbatim string format

autoload/fsharpbinding/python.vim, ftplugin/fsharp.vim, ftplugin/fsharpvim.py
This would resolve #23.
The method used in this pull request calls fsautocomplete with the command "compilerlocation" to get the paths. It only issues a call once at startup. I guess this would be the most reasonable solution.
What do you think, @kjnilsson?
=> Discover path to FSI and MSBuild/xbuild using fsautocomplete

autoload/fsharpbinding/python.vim
Users without Syntastic installed get spammed all the time by error messages in `OnCursorHold`. This change introduces a check that the command exists.
=> Check that vim has :SyntasticCheck before calling

ftplugin/fsharp.vim
On some systems, the plugin fails to initialize due to a 'TypeError'.
TypeError: argument of type 'NoneType' is not iterable.
The embedded python code initializes G.paths to an empty map;
however, if a key is not found in the map, the code re-initializes
G.paths using G.fsac.get_paths().  On some systems, the first call
to get_paths() returns 'None'.  Checking 'None' for the key raises
the error. Adding a call to G.fsac.get_paths() when fsac is
initialized avoids the race condition.  This change does not fix the underlying
race condition, but has been tested on both a system that exhibits
the behavior and one that does not.  Both test systems running the same
version of vim, python, mono, vim-fsharp and with the same .vimrc on arch Linux.
The only noticeable difference between the two …
=> Avoid race condition in get_path on some systems

ftplugin/fsharpvim.py
Give a more helpful error message if `fsautocomplete.exe` is not found on
Windows. "The system could not find the file specified" is right there
with "Undefined is not a function".
=> Give a more helpful error message if FSAutoComplete is not found on Windows

ftplugin/fsharpvim.py
I forgot to install Mono on my Mac and I ran into this. From what I read, `WindowsError` inherits from `OSError`, so there should not be any downsides to this.
=> Catch OSError instead of WindowsError.

syntax/fsharp.vim
I had a similar `remarks` section to the one below in my code, and noticed that the nested code region was not properly highlighted:
This PR fixes the issue by allowing the `fsharpXml` syntax element to contain itself.
=> fsharpXml should contain itself to allow nested markup

syntax/fsharp.vim
This PR fixes two syntax issues and introduces one improvement.
When a single-line comment is contained within a multi-line comment on the same line as the closing marker `*)`, like in the screenshot below, the regex of the single-line comment greedily matches the end of the multi-line comment `*)` such that the rest of the file is commented out (but can still be compiled etc.).
The other fix adds `private` to the list of function symbols so that the function name is correctly highlighted as with e.g. `rec`.
Backtick strings (for e.g. FsCheck) are now highlighted as regular strings. The differences can be seen below.
I am new to F#, but I hope that the changes are still valid. I tested the changes with some F# soure files from a project and it does not seem to break anything else.
=> Syntax improvements

README.mkd
Updating the header syntax to show correctly. Currently, there is no spacing which appears as invalid Markdown syntax on Github.
=> Update README.md header syntax

autoload/fsharpbinding/python.vim
Related to #74. Fixes access to the 'Errors' key in `errs` if `errs` is empty.
This PR needs to be verified.
=> Do not access 'Errors' if there are no current errors

ftplugin/fsharpvim.py
This is a quickfix for the Malformed JSON "non-IL or abstract method with non-zero RVA" error. The idea is to ignore any stdout messages which do not start with a '{'.
It is to be removed at next Mono release.
=> Temporary fix for unwanted stdout messages from Mono V5.0.1.1

README.mkd, ftplugin/fsi.py
Add a reference to the ```g:fsharp_interactive_bin``` variable to the readme for settings.  Also add a more detailed exception message when the fsi call fails.
Background: When I initially setup vim-fsharp on my machine, the default bin didn't work for me.  This pull request is intended to help others in the future diagnosis and resolve similar issues.
=> Expand doc and exception message regarding g:fsharp_interactive_bin

README.mkd, ftplugin/fsharp.vim
I presume the goal is to have the syntastic syntax checker enabled by default.  On my machine that wasn't the case.  This PR resolves the g:syntastic_fsharp_checkers variable not being set.
=> Enable syntastic checker (by default)

README.mkd, autoload/fsharpbinding/python.vim
This PR adds an optional feature to automatically show the fsi-out buffer when an FsiEval is run (if it's not already displayed). It's a small thing, but it saves the user from having to explicitly open the buffer to see execution results.  I also setup a global config value.  No default functionality was changed; this is an optional feature.
=> automatically show fsi-out buffer when executing fsieval

autoload/fsharpbinding/python.vim
Use bwipeout instead of bdelete when calling FsiReset.  bdelete keeps the "fsi-out" buffer in a "hidden" state, while bwipeout really removes the buffer.  This is significant because in the ```FsiEval``` call, ```if bufnr('fsi-out') == -1``` doesn't properly return -1 after a bdelete, so the fsi-out buffer doesn't come back as expected.
=> Really remove fsi-out buffer on FsiReset

README.mkd, autoload/fsharpbinding/python.vim, ftplugin/fsharp.vim, ftplugin/fsharpvim.py
This PR adds the ability to show triple-slash comments. If you like the functionality, but don't like where I have it wired in, let me know.  I'm flexible, but these seemed like the most logical places.
Method 1: <leader>h (help).  It's like <leader>t, but additionally displays expression comments/documentation if available.
Method 2: configuration variable ```g:fsharp_helptext_comments``` enables comments to be included in omni completion display.
Examples:
=> Add support for displaying triple-slash comments

autoload/fsharpbinding/python.vim, ftplugin/fsharp.vim, ftplugin/fsharpvim.py, ftplugin/fsi.py
When exiting, force-kill the python/mono process for fsautocomplete and fsi.  
Reason: I have run into semi-rare cases where the mono process hangs around after vim closes. In these cases mono manically consumes cpu and memory until it crashes. The force kill fixes this for me.
=> Ensure python/mono stop on exit

install.fsx
A while ago github switched to Tls12 only, that the default security protocol for .net will not work anymore.
Setting it manually fixes the problem.
=> install.fsx: use Tls12 when downloading
